sudo: false
language: cpp
install:
  - |
    pushd /tmp
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
    cd SDL2-2.0.9
    ./configure
    make
    sudo make install
    popd

  - cmake .
script: make
